services:
  postgres:
    image: postgres:16
    container_name: postgres_db_24
    restart: on-failure
    environment:
      POSTGRES_USER: camp
      POSTGRES_PASSWORD: 1234
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/club_cards
      - ENV_DATASOURCE_USERNAME=camp
      - ENV_DATASOURCE_PASSWORD=1234

volumes:
  postgres_data:
