services:
  postgres:
    image: postgres:16
    container_name: postgres_db_24
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_24:/var/lib/postgresql/data

  springboot-app:
    image: 10.4.56.75:32768/24_backend_t1
    restart: on-failure:5
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ENV_DATASOURCE_URL=r2dbc:postgresql://postgres:5432/club_cards
      - ENV_DATASOURCE_USERNAME=${POSTGRES_USER}
      - ENV_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data_24:
