services:
  springboot-app:
    image: club-card:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/club_cards
      - ENV_DATASOURCE_USERNAME=camp
      - ENV_DATASOURCE_PASSWORD=1234