CREATE DATABASE IF NOT EXISTS club_cards;

CREATE TABLE ClubMembers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    phoneNumber VARCHAR(20),
    role VARCHAR(50) NOT NULL,
    privilege VARCHAR(50) NOT NULL,
    balance DECIMAL(10, 2) DEFAULT 0.00
);